In [13]:
import pandas as pd
df= pd.read_csv('(raw) Weekly_data.csv')
df.head()

,week,future_return,volume,inventory,amount,BASIS,index_turnover_rate,short_balance_ratio,pli,t_spread,RSI,index_trading_volume,CCt+1
0,1,NaN,10.976047,8.185907,10.976047,59.2680,0.440,0.000005,0.00,2.04740,0.000000,6.510794,0.0
1,2,-0.056701,13.400486,10.345831,13.400486,31.7160,0.658,0.000010,0.20,2.01880,52.442353,8.499683,0.0
2,3,-0.028819,13.474156,10.799555,13.474156,34.6024,0.490,0.000027,0.20,1.97462,18.350791,8.218636,0.0
3,4,-0.042739,13.527370,10.820138,13.527370,57.0780,0.500,0.000028,0.25,1.94245,17.038370,7.993090,0.0
4,5,-0.048364,14.049264,11.179381,14.049264,16.1712,0.468,0.000056,0.60,1.89940,48.441850,8.089973,0.0

In [14]:
df.drop(df.columns[[1,2,3,4,5]], axis=1, inplace=True)
df.head()

,week,index_turnover_rate,short_balance_ratio,pli,t_spread,RSI,index_trading_volume,CCt+1
0,1,0.440,0.000005,0.00,2.04740,0.000000,6.510794,0.0
1,2,0.658,0.000010,0.20,2.01880,52.442353,8.499683,0.0
2,3,0.490,0.000027,0.20,1.97462,18.350791,8.218636,0.0
3,4,0.500,0.000028,0.25,1.94245,17.038370,7.993090,0.0
4,5,0.468,0.000056,0.60,1.89940,48.441850,8.089973,0.0

In [15]:
df0 = df[df['CCt+1']==0]
df1 = df[df['CCt+1']==1]

In [16]:
df0

,week,index_turnover_rate,short_balance_ratio,pli,t_spread,RSI,index_trading_volume,CCt+1
0,1,0.440,0.000005,0.00,2.04740,0.000000,6.510794,0.0
1,2,0.658,0.000010,0.20,2.01880,52.442353,8.499683,0.0
2,3,0.490,0.000027,0.20,1.97462,18.350791,8.218636,0.0
3,4,0.500,0.000028,0.25,1.94245,17.038370,7.993090,0.0
4,5,0.468,0.000056,0.60,1.89940,48.441850,8.089973,0.0
...,...,...,...,...,...,...,...,...
646,647,0.436,0.126962,0.60,0.73854,24.064675,9.153984,0.0
647,648,0.520,0.109330,0.60,0.79608,61.873567,9.428150,0.0
648,649,0.534,0.099007,0.80,0.73406,77.835251,9.467997,0.0
649,650,0.354,0.116676,0.40,0.70614,23.634396,9.166686,0.0
650,651,0.282,0.143002,0.40,0.67266,7.326473,8.939615,0.0

In [17]:
df1

,week,index_turnover_rate,short_balance_ratio,pli,t_spread,RSI,index_trading_volume,CCt+1
75,76,0.2540,0.002680,0.400000,0.253600,46.828693,7.649112,1.0
77,78,0.3020,0.002770,0.400000,0.517420,81.294206,7.750791,1.0
266,267,1.7420,0.004257,0.200000,1.831280,27.716169,10.336207,1.0
267,268,1.8300,0.003928,0.500000,1.775725,30.885954,10.088124,1.0
268,269,2.0460,0.002911,0.200000,1.749200,60.607379,10.365685,1.0
269,270,2.5120,0.002487,0.600000,1.507680,52.496232,10.436896,1.0
270,271,1.7560,0.002346,0.600000,1.187760,44.100536,10.172173,1.0
271,272,1.4900,0.002504,0.600000,1.131940,46.376060,10.076136,1.0
272,273,1.3020,0.002811,0.400000,1.208380,27.360980,9.907758,1.0
274,275,1.1800,0.002741,0.400000,1.303580,83.502842,9.808332,1.0
275,276,1.0920,0.003193,0.400000,1.264060,15.090838,9.705496,1.0
276,277,1.2000,0.003923,0.400000,1.201520,45.718205,9.591516,1.0
277,278,1.3900,0.004212,0.666667,1.063850,75.867769,9.217301,1.0
278,279,0.7100,0.005284,0.400000,1.063160,57.136787,9.156135,1.0
400,401,0.6300,0.010125,0.400000,0.418840,30.371643,9.275781,1.0
401,402,0.7340,0.010003,0.200000,0.545667,2.618270,9.396089,1.0
403,404,0.3950,0.015554,1.000000,0.582600,100.000000,7.888072,1.0
406,407,0.4040,0.010921,0.400000,0.639760,39.892939,8.870785,1.0
407,408,0.4040,0.011247,0.400000,0.563260,15.595348,8.876353,1.0
408,409,0.4180,0.010279,0.600000,0.553920,38.339003,8.958929,1.0
410,411,0.3500,0.012031,0.400000,0.613220,64.952546,8.704660,1.0
411,412,0.3800,0.011593,0.400000,0.709080,35.335313,8.782990,1.0
420,421,0.3925,0.017262,0.500000,0.428675,14.759702,8.540763,1.0
421,422,0.3020,0.019872,0.200000,0.385060,65.363627,8.553791,1.0
615,616,0.4800,0.097191,0.400000,0.777620,53.210843,9.402249,1.0
617,618,0.5940,0.087201,0.600000,0.927900,40.311683,9.560544,1.0
641,642,0.3200,0.134501,0.200000,1.020920,13.218831,9.188349,1.0

In [18]:
df0.mean(axis = 0, skipna = True)

week                    325.038462
index_turnover_rate       0.499128
short_balance_ratio       0.034402
pli                       0.520459
t_spread                  0.785972
RSI                      51.689754
index_trading_volume      8.658167
CCt+1                     0.000000
dtype: float64

In [19]:
df1.mean(axis = 0, skipna = True)

week                    348.222222
index_turnover_rate       0.911463
short_balance_ratio       0.018290
pli                       0.439506
t_spread                  0.934284
RSI                      44.776015
index_trading_volume      9.268927
CCt+1                     1.000000
dtype: float64